required = [
  "k8s.io/code-generator/cmd/client-gen",
  # needed by generated clientsets, but not an explicit dep in client-gen itself
  "k8s.io/apimachinery/pkg/apimachinery/registered",

  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/apiextensions-apiserver"
]

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/heptiolabs/healthcheck"

[[override]]
  name = "k8s.io/api"
  version="kubernetes-1.10.1"

[[override]]
  name = "k8s.io/apimachinery"
  version="kubernetes-1.10.1"

[[override]]
  name = "k8s.io/client-go"
  version = "v7.0.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.1"

# Override for github.com/heptiolabs/healthcheck
[[override]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  go-tests = true
  unused-packages = true
